import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.eclipse.rdf4j.repository.Repository;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.LinkedList;

/**
 * Created by christine on 19.01.17.
 */

/**
 * Dialog to manually add a book
 */
public class AddBookDialog extends JDialog {
    private JTextField titleTextField;
    private JTextField urlCoverTextField;
    private JTextField publicationYearTextField;
    private JTextField genreTextField;
    private JTextField languageTextField;
    private JTextField isbnTextField;
    private JComboBox<String> authorComboBox;
    private JComboBox<String> publisherComboBox;
    private JOptionPane optionPane;
    private Repository repo;
    public JPanel addBookView;


    public AddBookDialog(Frame aFrame, String filePath) {
        super(aFrame, true);
        repo = FileHandler.readRepositoryFromFile(filePath);
        LinkedList<String> authors = RepoHandler.getAll(repo, "Author"); //get all authors in the repo
        LinkedList<String> publisher = RepoHandler.getAll(repo, "Publisher"); //get all publisher in the repo

        authorComboBox.addItem("Please select an author"); //First item that should be shown in the comboBox
        authorComboBox.addItem("New Author"); //Used to allow the user to add a new author
        for (String a : authors) {
            authorComboBox.addItem(a); //add all authors of the repo to the comboBox
        }

        //add itemListener to react when the user wants to add a new author
        authorComboBox.addItemListener(new AuthorSelected());


        publisherComboBox.addItem("Please select a publisher");//First item that should be shown in the comboBox
        publisherComboBox.addItem("New Publisher"); //Used to allow the user to add a new publisher
        for (String p : publisher) {
            publisherComboBox.addItem(p); //add all publishers of the repo to the comboBox
        }

        //add itemListener to react when the user wants to add a new publisher
        publisherComboBox.addItemListener(new PublisherSelected());

        Object[] options = {"Save", "Cancel"}; // the two options the user can select in the optionPane
        optionPane = new JOptionPane(getAddBookView(), JOptionPane.PLAIN_MESSAGE, JOptionPane.OK_CANCEL_OPTION, null, options, options[0]);
        setContentPane(optionPane);
        optionPane.addPropertyChangeListener(new MyPropertyChangeListener());
        pack();
    }

    /**
     * set the dialog to visible and return "Save" or "Cancel" depending on what the user clicks
     *
     * @return
     */
    public String showDialog() {
        setVisible(true);
        return optionPane.getValue().toString();
    }

    public JPanel getAddBookView() {
        return addBookView;
    }

    public String getTitle() {
        return titleTextField.getText();
    }

    public String getUrlCover() {
        return urlCoverTextField.getText();
    }

    public String getPublicationYear() {
        return publicationYearTextField.getText();
    }

    public String getGenre() {
        return genreTextField.getText();
    }

    public String getLanguage() {
        return languageTextField.getText();
    }

    public String getIsbn() {
        return isbnTextField.getText();
    }

    public String getAuthor() {
        return authorComboBox.getSelectedItem().toString();
    }

    public String getPublisher() {
        return publisherComboBox.getSelectedItem().toString();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        addBookView = new JPanel();
        addBookView.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setFont(new Font(label1.getFont().getName(), label1.getFont().getStyle(), 48));
        label1.setHorizontalTextPosition(0);
        label1.setText("Book Manager");
        addBookView.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(8, 1, new Insets(0, 0, 0, 0), -1, -1));
        addBookView.add(panel1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Title");
        panel2.add(label2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        titleTextField = new JTextField();
        panel2.add(titleTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel3, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("URL Cover");
        panel3.add(label3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        urlCoverTextField = new JTextField();
        panel3.add(urlCoverTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel4, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Publication Year");
        panel4.add(label4, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        publicationYearTextField = new JTextField();
        panel4.add(publicationYearTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel5, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("Genre");
        panel5.add(label5, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        genreTextField = new JTextField();
        panel5.add(genreTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel6, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label6 = new JLabel();
        label6.setText("Publisher");
        panel6.add(label6, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        publisherComboBox = new JComboBox();
        panel6.add(publisherComboBox, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel7 = new JPanel();
        panel7.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel7, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label7 = new JLabel();
        label7.setText("Language");
        panel7.add(label7, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        languageTextField = new JTextField();
        panel7.add(languageTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JPanel panel8 = new JPanel();
        panel8.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel8, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label8 = new JLabel();
        label8.setText("Author");
        panel8.add(label8, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        authorComboBox = new JComboBox();
        panel8.add(authorComboBox, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel9 = new JPanel();
        panel9.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel9, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label9 = new JLabel();
        label9.setText("ISBN*");
        panel9.add(label9, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        isbnTextField = new JTextField();
        isbnTextField.setColumns(13);
        isbnTextField.setEditable(true);
        isbnTextField.setEnabled(true);
        panel9.add(isbnTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        label2.setLabelFor(titleTextField);
        label3.setLabelFor(urlCoverTextField);
        label4.setLabelFor(publicationYearTextField);
        label5.setLabelFor(genreTextField);
        label6.setLabelFor(publisherComboBox);
        label7.setLabelFor(languageTextField);
        label8.setLabelFor(authorComboBox);
        label9.setLabelFor(isbnTextField);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return addBookView;
    }

    /**
     * Class to allow the user to add a new author
     */
    private class AuthorSelected implements ItemListener {

        @Override
        public void itemStateChanged(ItemEvent e) {
            if (e.getStateChange() == ItemEvent.SELECTED  //if a new item is selected and it is "New Author"
                    && authorComboBox.getSelectedItem().toString().equals("New Author")) {

                //Create an new Dialog to enter the information about the author
                Object[] options = {"Save", "Cancel"};
                AddAuthorPanel aap = new AddAuthorPanel();
                int o = JOptionPane.showOptionDialog(null, aap.getAuthorView(), "Add Author", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);

                if (o == JOptionPane.YES_OPTION) { //if the user wants to save the author

                    //get all the information and construct an id
                    String firstName = aap.getFirstName();
                    String lastName = aap.getLastName();
                    String gender = aap.getGender();
                    String dob = aap.getDateOfBirth();
                    String id = firstName + "_" + lastName + "_" + dob;


                    if (!id.equals("  ")) { //if the id is not empty
                        Author a = new Author(id, gender, firstName, lastName, dob); //create a new author
                        ModelHandler.addAuthor(a, MainWindow.getModel()); //add it to the model
                        authorComboBox.addItem(id); //add the item to the combobox
                        authorComboBox.setSelectedItem(id); //select the item in the combobox
                    } else { // if the id is empty don't save the author and reset the selected item in the combobox
                        authorComboBox.setSelectedItem("Please select an author");
                    }
                } else { //if the user selects cancel reset the selected item in the combobox
                    authorComboBox.setSelectedItem("Please select an author");
                }
            }

        }
    }

    /**
     * Class to allow the user to add a new publisher
     */
    private class PublisherSelected implements ItemListener {

        @Override
        public void itemStateChanged(ItemEvent e) {
            if (e.getStateChange() == ItemEvent.SELECTED && //if a new item is selected and it is "New Publisher"
                    publisherComboBox.getSelectedItem().toString().equals("New Publisher")) {

                // Show a input dialog where the user enters the publisher name, which is also the id
                String publisher = JOptionPane.showInputDialog(null, "Please enter the publisher name", "New Publisher", JOptionPane.PLAIN_MESSAGE);
                if (publisher != null && !publisher.equals("")) { //if the entered string is not empty

                    if (RepoHandler.searchWithFilter(repo, "FILTER(?publisher = ex:" + publisher + ")").size() == 0) {
                        Publisher p = new Publisher(publisher); //create a new publisher
                        ModelHandler.addPublisher(p, MainWindow.getModel()); //add the publisher to the model
                        publisherComboBox.addItem(publisher); //add the publisher to the combobox
                        publisherComboBox.setSelectedItem(publisher); //select the publisher in the combobox
                    } else {
                        JOptionPane.showMessageDialog(null, "This publisher ID exists already.", "Error", JOptionPane.ERROR_MESSAGE);
                        publisherComboBox.setSelectedItem("Please select a publisher");
                    }

                } else {
                    //if the entered string is empty, reset the combobox to the intial value
                    publisherComboBox.setSelectedItem("Please select a publisher");

                }
            }
        }
    }

    /**
     * Class used to allow the user to exit from the dialog
     */
    private class MyPropertyChangeListener implements PropertyChangeListener {

        @Override
        public void propertyChange(PropertyChangeEvent evt) {
            String prop = evt.getPropertyName();
            if (isVisible() && evt.getSource() == optionPane && prop.equals(JOptionPane.VALUE_PROPERTY)) {
                boolean okToClose = true;
                if (evt.getNewValue().equals("Save")) { //if the user clicked on save

                    //check the input for correctness and that isbn is not missing
                    if (isbnTextField.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Please enter the ISBN number!", "Error", JOptionPane.ERROR_MESSAGE);
                        okToClose = false;
                    }

                    if (!publicationYearTextField.getText().equals("")) {
                        try {
                            Integer.parseInt(publicationYearTextField.getText());
                        } catch (NumberFormatException nfe) {
                            JOptionPane.showMessageDialog(null, "Publication Year needs to be a number!", "Error", JOptionPane.ERROR_MESSAGE);
                            okToClose = false;
                        }
                    }
                } else if (evt.getNewValue().equals("wait")) { //used to keep the dialog open, if the input was not ok
                    okToClose = false;
                }
                if (okToClose) {
                    setVisible(false);
                } else { //if the user clicked on "Save" but the input was not ok
                    //set the value of the optionPane to an intermediate value,
                    // so that when the user clicks again on "Save" the listener fires again
                    optionPane.setValue("wait");
                }
            }
        }
    }
}
